name: bayesian-network-playground
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - streamlit>=1.28.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - plotly>=5.15.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - networkx>=3.1
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - jupyter>=1.0.0
  - notebook>=6.5.0
  - pip:
    - pgmpy>=0.1.20
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - black>=23.0.0
    - flake8>=6.0.0
    - bokeh>=3.2.0
    - altair>=5.0.0
    - numba>=0.57.0
    - cython>=3.0.0 